services:
  - type: web
    name: tripwise-ai-backend
    runtime: docker
    rootDir: Backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: models/gemini-flash-lite-latest
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: FRONTEND_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: tripewiseai
      - key: WEATHER_API_KEY
        sync: false
      - key: ADMIN_SECRET
        sync: false
