from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel

from app.schemas import TripGenerationRequest
from app.services.openai_service import OpenAIService

router = APIRouter(prefix="/api/trips", tags=["Trips"])

# Single shared instance — client is initialised once at startup
_openai_service = OpenAIService()


class ItineraryResponse(BaseModel):
    itinerary: str


@router.post(
    "/generate",
    response_model=ItineraryResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate an AI travel itinerary",
)
def generate_trip(payload: TripGenerationRequest):
    """
    Accepts trip details and returns a markdown itinerary generated by GPT-4o-mini.
    """
    try:
        itinerary = _openai_service.generate_itinerary(
            source=payload.source,
            destination=payload.destination,
            days=payload.days,
            travelers=payload.travelers,
            budget=payload.budget,
        )
        return ItineraryResponse(itinerary=itinerary)

    except RuntimeError as e:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=str(e),
        )
