"""initial_schema

Revision ID: ee0ab6e3bc74
Revises: 
Create Date: 2026-06-11 15:35:38.735915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql


def _json_type():
    """Use JSONB on PostgreSQL, JSON on SQLite."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        return _json_type()
    return sa.JSON()


def _uuid_type():
    """Use native UUID on PostgreSQL, String(36) on SQLite."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        return postgresql.UUID(as_uuid=True)
    return sa.String(36)

# revision identifiers, used by Alembic.
revision: str = 'ee0ab6e3bc74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('attraction_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('location_coordinates', _json_type(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_attraction_rating_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attractions_category'), 'attractions', ['category'], unique=False)
    op.create_index(op.f('ix_attractions_city'), 'attractions', ['city'], unique=False)
    op.create_table('destination_comparisons',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('destination_one', sa.String(length=255), nullable=False),
    sa.Column('destination_two', sa.String(length=255), nullable=False),
    sa.Column('budget_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('safety_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('weather_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('crowd_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('nightlife_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.CheckConstraint('budget_score    >= 0 AND budget_score    <= 10', name='ck_budget_score'),
    sa.CheckConstraint('crowd_score     >= 0 AND crowd_score     <= 10', name='ck_crowd_score'),
    sa.CheckConstraint('nightlife_score >= 0 AND nightlife_score <= 10', name='ck_nightlife_score'),
    sa.CheckConstraint('safety_score    >= 0 AND safety_score    <= 10', name='ck_safety_score'),
    sa.CheckConstraint('weather_score   >= 0 AND weather_score   <= 10', name='ck_weather_score'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_comparisons_destination_one'), 'destination_comparisons', ['destination_one'], unique=False)
    op.create_index(op.f('ix_destination_comparisons_destination_two'), 'destination_comparisons', ['destination_two'], unique=False)
    op.create_table('hidden_gems',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('place_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommended_for', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hidden_gems_city'), 'hidden_gems', ['city'], unique=False)
    op.create_table('hotels',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('hotel_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('amenities', _json_type(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_hotels_rating_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_table('travel_packages',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('agency_name', sa.String(length=255), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('package_description', sa.Text(), nullable=True),
    sa.Column('inclusions', _json_type(), nullable=True),
    sa.Column('exclusions', _json_type(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_days > 0', name='ck_packages_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_packages_destination'), 'travel_packages', ['destination'], unique=False)
    op.create_index(op.f('ix_travel_packages_price'), 'travel_packages', ['price'], unique=False)
    op.create_table('users',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weather_data_cache',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'forecast_date', name='uq_weather_city_date')
    )
    op.create_index(op.f('ix_weather_data_cache_city'), 'weather_data_cache', ['city'], unique=False)
    op.create_index(op.f('ix_weather_data_cache_forecast_date'), 'weather_data_cache', ['forecast_date'], unique=False)
    op.create_table('ai_chat_history',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('user_id', _uuid_type(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_history_created_at'), 'ai_chat_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_history_user_id'), 'ai_chat_history', ['user_id'], unique=False)
    op.create_table('ai_trip_suggestions',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('user_id', _uuid_type(), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('suggested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_trip_suggestions_user_id'), 'ai_trip_suggestions', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('user_id', _uuid_type(), nullable=False),
    sa.Column('hotel_id', _uuid_type(), nullable=True),
    sa.Column('package_id', _uuid_type(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hotel_id IS NOT NULL OR package_id IS NOT NULL', name='ck_review_target'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['travel_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_hotel_id'), 'reviews', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_reviews_package_id'), 'reviews', ['package_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('user_id', _uuid_type(), nullable=False),
    sa.Column('source_location', sa.String(length=255), nullable=False),
    sa.Column('destination_location', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('number_of_days', sa.Integer(), nullable=False),
    sa.Column('number_of_travelers', sa.Integer(), nullable=False),
    sa.Column('travel_mode', sa.String(length=50), nullable=True),
    sa.Column('total_estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('trip_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('number_of_days > 0', name='ck_trips_days_positive'),
    sa.CheckConstraint('number_of_travelers > 0', name='ck_trips_travelers_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_destination_location'), 'trips', ['destination_location'], unique=False)
    op.create_index(op.f('ix_trips_trip_status'), 'trips', ['trip_status'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('user_id', _uuid_type(), nullable=False),
    sa.Column('preferred_budget', sa.String(length=50), nullable=True),
    sa.Column('travel_styles', _json_type(), nullable=True),
    sa.Column('preferred_climates', _json_type(), nullable=True),
    sa.Column('dietary_needs', _json_type(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('hotel_recommendations',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('trip_id', _uuid_type(), nullable=False),
    sa.Column('hotel_id', _uuid_type(), nullable=False),
    sa.Column('recommendation_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('recommendation_score >= 0 AND recommendation_score <= 10', name='ck_rec_score_range'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'hotel_id', name='uq_hotel_rec_trip_hotel')
    )
    op.create_index(op.f('ix_hotel_recommendations_hotel_id'), 'hotel_recommendations', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_recommendations_trip_id'), 'hotel_recommendations', ['trip_id'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('trip_id', _uuid_type(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('activities', _json_type(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('day_number > 0', name='ck_itineraries_day_positive'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'day_number', name='uq_itineraries_trip_day')
    )
    op.create_index(op.f('ix_itineraries_trip_id'), 'itineraries', ['trip_id'], unique=False)
    op.create_table('saved_trips',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('user_id', _uuid_type(), nullable=False),
    sa.Column('trip_id', _uuid_type(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trip_id', name='uq_saved_trip_user_trip')
    )
    op.create_index(op.f('ix_saved_trips_user_id'), 'saved_trips', ['user_id'], unique=False)
    op.create_table('trip_expenses',
    sa.Column('id', _uuid_type(), nullable=False),
    sa.Column('trip_id', _uuid_type(), nullable=False),
    sa.Column('transport_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hotel_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('food_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activity_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('miscellaneous_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_expenses_trip_id'), 'trip_expenses', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_expenses_trip_id'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    op.drop_index(op.f('ix_saved_trips_user_id'), table_name='saved_trips')
    op.drop_table('saved_trips')
    op.drop_index(op.f('ix_itineraries_trip_id'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_hotel_recommendations_trip_id'), table_name='hotel_recommendations')
    op.drop_index(op.f('ix_hotel_recommendations_hotel_id'), table_name='hotel_recommendations')
    op.drop_table('hotel_recommendations')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_trip_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination_location'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_package_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_hotel_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_ai_trip_suggestions_user_id'), table_name='ai_trip_suggestions')
    op.drop_table('ai_trip_suggestions')
    op.drop_index(op.f('ix_ai_chat_history_user_id'), table_name='ai_chat_history')
    op.drop_index(op.f('ix_ai_chat_history_created_at'), table_name='ai_chat_history')
    op.drop_table('ai_chat_history')
    op.drop_index(op.f('ix_weather_data_cache_forecast_date'), table_name='weather_data_cache')
    op.drop_index(op.f('ix_weather_data_cache_city'), table_name='weather_data_cache')
    op.drop_table('weather_data_cache')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_travel_packages_price'), table_name='travel_packages')
    op.drop_index(op.f('ix_travel_packages_destination'), table_name='travel_packages')
    op.drop_table('travel_packages')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_hidden_gems_city'), table_name='hidden_gems')
    op.drop_table('hidden_gems')
    op.drop_index(op.f('ix_destination_comparisons_destination_two'), table_name='destination_comparisons')
    op.drop_index(op.f('ix_destination_comparisons_destination_one'), table_name='destination_comparisons')
    op.drop_table('destination_comparisons')
    op.drop_index(op.f('ix_attractions_city'), table_name='attractions')
    op.drop_index(op.f('ix_attractions_category'), table_name='attractions')
    op.drop_table('attractions')
    # ### end Alembic commands ###
